services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      JWT_KEY: ${JWT_KEY}
      NEON_CONNSTR: ${NEON_CONNSTR}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    depends_on:
      redis:
        condition: service_started
  redis:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"
volumes:
  db_data:
