services:
  - type: web
    name: app
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: db
          property: port
      - key: DB_USER
        fromDatabase:
          name: db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: db
          property: database
      - key: JWT_KEY
        sync: false

  - type: redis
    name: redis
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    plan: free
    region: oregon

databases:
  - name: db
    databaseName: ${POSTGRES_DB} # Will need to be set in Render environment
    user: ${POSTGRES_USER} # Will need to be set in Render environment
    plan: free # Choose appropriate plan
    region: oregon # You can change this to your preferred region
